name: Release Go Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux
            arch: amd64
          - platform: linux
            arch: arm64
          - platform: darwin
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Build binary
        run: |
          go build -o beachhead-${{ matrix.platform }}-${{ matrix.arch }} .

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}_${{ matrix.arch }}
          path: ${{ format('beachhead-{0}-{1}', matrix.platform, matrix.arch) }}
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Generate checksums
        run: |
          cd ./artifacts
          echo "Generating checksums..."
          find . -type f -not -name "*.sha256" -not -path "*/\.*" | sort | xargs sha256sum > checksums.txt
          cat checksums.txt

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./artifacts/**/*
            ./artifacts/checksums.txt
